Repository gardener/gardener-extension-os-suse-chost, pull requests merged in 2023-07, with the labels that each got.

#95 Drop support for Shoots with Kubernetes version < 1.22
  charts/gardener-extension-os-suse-chost/templates/poddisruptionbudget.yaml
  example/controller-registration.yaml
Labels: kind/cleanup, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs, merge/squash

#96 Introduce persona-based docs
  .docforge/manifest.yaml
  docs/usage/usage.md
Labels: kind/cleanup, needs/ok-to-test, reviewed/lgtm, size/xs

#97 Fixed broken links - 2023.07
  README.md
Labels: area/documentation, kind/enhancement, needs/ok-to-test, needs/review, size/xs, area/os, os/suse-chost
