Repository gardener/gardener-extension-os-suse-chost, pull requests merged in 2024-08, with the labels that each got.

#165 Switch VPA's API version to `autoscaling.k8s.io/v1`
  charts/gardener-extension-os-suse-chost/templates/vpa.yaml
  example/controller-registration.yaml
Labels: kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs, area/os, os/suse-chost

#156 Removed broken link - 2024.07
  README.md
Labels: area/documentation, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs, area/os, os/suse-chost

#162 Publish Helm charts as OCI artifacts
  .ci/pipeline_definitions
Labels: area/delivery, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs, area/os, os/suse-chost
