Repository gardener/gardener-extension-os-suse-chost, pull requests merged in 2025-08, with the labels that each got.

#253 export testresults as inlined ocm-resource
  .github/workflows/build.yaml
Labels: kind/task, reviewed/ok-to-test, reviewed/lgtm, size/s, area/os, os/suse-chost, area/compliance

#261 add helmcharts (again)
  .github/workflows/build.yaml
Labels: area/delivery, kind/bug, kind/regression, reviewed/ok-to-test, reviewed/lgtm, size/xs, os/suse-chost

#263 update CI build status badge (again)
  README.md
Labels: kind/cleanup, reviewed/ok-to-test, reviewed/lgtm, size/xs, area/os, os/suse-chost

#266 ci: fix permission for pull_request_target in conjunction with trusted label
  .github/workflows/build.yaml
Labels: reviewed/ok-to-test, reviewed/lgtm, size/xs
